d = d

WINDOW_MANAGER = WINDOW_MANAGER
EVENT_MANAGER = EVENT_MANAGER
SLASH_COMMANDS = SLASH_COMMANDS
SCENE_MANAGER = SCENE_MANAGER
ANIMATION_MANAGER = ANIMATION_MANAGER

GuiRoot = GuiRoot
CENTER = CENTER
TOPLEFT = TOPLEFT
BOTTOMRIGHT = BOTTOMRIGHT
RIGHT = RIGHT
LEFT = LEFT
TOPRIGHT = TOPRIGHT
TOP = TOP
BOTTOMLEFT = BOTTOMLEFT
GetControl = GetControl

CT_BACKDROP = CT_BACKDROP
CT_LABEL = CT_LABEL
CT_TEXTURE = CT_TEXTURE
CT_CONTROL = CT_CONTROL
CT_SCROLL = CT_SCROLL
CT_SLIDER = CT_SLIDER

CURT_MONEY = CURT_MONEY
CURT_CHAOTIC_CREATIA = CURT_CHAOTIC_CREATIA
CURT_TELVAR_STONES = CURT_TELVAR_STONES
CURRENCY_LOCATION_CHARACTER = CURRENCY_LOCATION_CHARACTER
CURRENCY_LOCATION_BANK = CURRENCY_LOCATION_BANK
CURRENCY_LOCATION_ACCOUNT = CURRENCY_LOCATION_ACCOUNT

EVENT_ADD_ON_LOADED = EVENT_ADD_ON_LOADED
EVENT_EFFECT_CHANGED = EVENT_EFFECT_CHANGED
EVENT_PLAYER_DEAD = EVENT_PLAYER_DEAD
EVENT_PLAYER_ALIVE = EVENT_PLAYER_ALIVE
EVENT_PLAYER_ACTIVATED = EVENT_PLAYER_ACTIVATED
EVENT_ZONE_UPDATE = EVENT_ZONE_UPDATE
EVENT_MONEY_UPDATE = EVENT_MONEY_UPDATE
EVENT_TELVAR_STONE_UPDATE = EVENT_TELVAR_STONE_UPDATE

EFFECT_RESULT_FADED = EFFECT_RESULT_FADED

SCENE_FRAGMENT_SHOWN = SCENE_FRAGMENT_SHOWN
SCENE_FRAGMENT_HIDDEN = SCENE_FRAGMENT_HIDDEN
PushActionLayerByName = PushActionLayerByName
RemoveActionLayerByName = RemoveActionLayerByName

---@type fun(data: {id: string, name: string, callback: fun(), unselectedCallback: fun()})
ZO_GameMenu_AddSettingPanel = ZO_GameMenu_AddSettingPanel
ZO_FadeSceneFragment = ZO_FadeSceneFragment
ZO_HUDFadeSceneFragment = ZO_HUDFadeSceneFragment

HUD_SCENE = HUD_SCENE
HUD_UI_SCENE = HUD_UI_SCENE

SKILL_TYPE_NONE = SKILL_TYPE_NONE
GetSkillLineIndicesFromSkillLineId = GetSkillLineIndicesFromSkillLineId
GetNumBuffs = GetNumBuffs
GetUnitBuffInfo = GetUnitBuffInfo
GetCurrentCharacterId = GetCurrentCharacterId
GetUnitName = GetUnitName
GetWorldName = GetWorldName

REGISTER_FILTER_ABILITY_ID = REGISTER_FILTER_ABILITY_ID
REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE = REGISTER_FILTER_SOURCE_COMBAT_UNIT_TYPE
COMBAT_UNIT_TYPE_PLAYER = COMBAT_UNIT_TYPE_PLAYER

SCROLL_BOUNDING_CONTAINED = SCROLL_BOUNDING_CONTAINED
ORIENTATION_VERTICAL = ORIENTATION_VERTICAL

ZO_ScrollList_GetData = ZO_ScrollList_GetData
ZO_ScrollList_SelectData = ZO_ScrollList_SelectData
ZO_ScrollList_AddDataType = ZO_ScrollList_AddDataType
ZO_ScrollList_EnableSelection = ZO_ScrollList_EnableSelection
ZO_ScrollList_GetDataTypeTable = ZO_ScrollList_GetDataTypeTable
ZO_ScrollList_GetDataList = ZO_ScrollList_GetDataList
ZO_ScrollList_Clear = ZO_ScrollList_Clear
ZO_ScrollList_CreateDataEntry = ZO_ScrollList_CreateDataEntry
ZO_ScrollList_Commit = ZO_ScrollList_Commit

TEXT_ALIGN_LEFT = TEXT_ALIGN_LEFT
TEXT_ALIGN_CENTER = TEXT_ALIGN_CENTER
TEXT_WRAP_MODE_ELLIPSIS = TEXT_WRAP_MODE_ELLIPSIS

GetCurrencyAmount = GetCurrencyAmount
GetCurrencyKeyboardIcon = GetCurrencyKeyboardIcon

zo_iconFormat = zo_iconFormat

ZO_PerformanceMeters = ZO_PerformanceMeters
ZO_SavedVars = ZO_SavedVars

ZO_Tooltips_ShowTextTooltip = ZO_Tooltips_ShowTextTooltip
ZO_Tooltips_HideTextTooltip = ZO_Tooltips_HideTextTooltip
