d = d

WINDOW_MANAGER = WINDOW_MANAGER
EVENT_MANAGER = EVENT_MANAGER
SLASH_COMMANDS = SLASH_COMMANDS

GuiRoot = GuiRoot
CENTER = CENTER
TOPLEFT = TOPLEFT
BOTTOMRIGHT = BOTTOMRIGHT
RIGHT = RIGHT

CT_LABEL = CT_LABEL
CT_TEXTURE = CT_TEXTURE

EVENT_ADD_ON_LOADED = EVENT_ADD_ON_LOADED